# These are supported funding model platforms

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# liberapay: borkbackup
custom: ['https://www.borkbackup.org/support/fund.html']
