sudo: required

language: python

cache:
    directories:
        - $HOME/.cache/pip

matrix:
    include:
        - python: 3.4
          os: linux
          dist: trusty
          env: TOXENV=py34
        - python: 3.5
          os: linux
          dist: trusty
          env: TOXENV=py35
        - python: 3.6
          os: linux
          dist: trusty
          env: TOXENV=py36
        - python: 3.5
          os: linux
          dist: trusty
          env: TOXENV=flake8
        - language: generic
          os: osx
          osx_image: xcode6.4
          env: TOXENV=py34
        - language: generic
          os: osx
          osx_image: xcode6.4
          env: TOXENV=py35
        - language: generic
          os: osx
          osx_image: xcode6.4
          env: TOXENV=py36

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
    - ./.travis/upload_coverage.sh

notifications:
    irc:
        channels:
            - "irc.freenode.org#borgbackup"
        use_notice: true
        skip_join: true
