language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "sudo add-apt-repository -y ppa:gezakovacs/lz4"
  - "sudo apt-get update"
  - "sudo apt-get install -y liblz4-dev"
  - "sudo apt-get install -y libacl1-dev"
  - "pip install --use-mirrors Cython"
  - "pip install -e ."
# command to run tests
script: fakeroot -u py.test
